include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    sort_constructors_first: true
    sort_child_properties_last: true
    use_super_parameters: true
    avoid_print: true
    prefer_relative_imports: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_is_empty: true
    prefer_is_not_empty: true
